### ISSUE TITLE
Item ID results to issue

### ISSUE THREAD

**Issue by schmiddel89** [DenizenScript/Denizen-For-Bukkit#1114]
Hey there got an issue with denizen and the plugin shopkeepers... Like the developer said the item-id of denizen items won't show anymore but in the villager trade it is shown anyway... So this results to bugs! If I want to trade for example a denizen item for a stone then in the field below the stone will not be displayed. But when I click at this empty field (where actually should be the stone, for closing the trade) the trade still works. Pls fix the item id in the villager trade... :)

**Comment by Morphan1** [comment]
This should be fixed in the latest development build
http://ci.mineconomy.org/job/Denizen_Developmental/lastSuccessfulBuild/

**Comment by mcmonkey4eva** [comment]
... Well, is it fixed?

**Comment by blablubbabc** [comment]
@Morphan1 Regarding the issue with the villager sometimes not accepting the denizen item (which we slightly talked about on the shopkeepers project page):

I have been debugging the issue now and found out that:
* If you let denizen give you a custom denizen item, it adds this invisible color codes code to the bottom of the lore.
* If you go into creative mode and copy the item stack (middle-mouse click on the itemstack), the source stack (which is left in the slot) will have the invisible color codes code at the top of the lore now for some reason.
* If you setup a shopkeeper trade with this item (which now has the color codes in the top lore line), and then try to trade a freshly given denizen item which has the color codes in the bottom line, minecraft won't accept the trade.

I don't know why minecraft suddenly rearranges this invisible lore line. Maybe you could try to debug this as well and temporary disable the hiding of the color codes lore line from the client: If the lore lines still get reorderd on itemstack copy, then this might be a minecraft bug. If not, then hiding the invisible lore line from the client might somehow be the cause of the issue.

**Comment by mcmonkey4eva** [comment]
No, the lore was definitely in the wrong spot. @Morphan1 made a minor screwup when handling creative packets... not major, I fixed that much in the commit above ^ (and in the latest dev build).

**Comment by blablubbabc** [comment]
@mcmonkey4eva 
The top lore line of the item seems to get replaced now. Probably because of this change: https://github.com/mcmonkey4eva/Denizen/commit/9b46dc81778cdfc2a6551b84d3f0a5be457841aa

Another thing I noticed during testing, probably also related to this packet manipulation stuff for this denizen items (might better fit into a separate ticket though):

During my testing I was spam clicking stacks of the denizen created items quite a lot (partly with left and right mouse button at the same time) in the inventory, also splitting the stack, and re-combining it again. And from time to time (quite frequently actually, in a matter of a bunch of seconds up to about a minute at max) some or all of those denizen items went lost (simply disappeared from the inventory). They were not dropped, and refreshing the inventory by relogging to the server also didn't bring those items back up..

**Comment by mcmonkey4eva** [comment]
The Creative-mode client has full control of their own inventory... anything the creative client deletes is straight gone. It's a lot more stable in survival where the server has power.

ALSO: The coming dev build should fix a few issues. (Currently in the process of building)

**Comment by blablubbabc** [comment]
The issue with the disapearing items is happening in survival mode as well (I even have the feeling that it's easier in survival mode to reproduce this). I will try with the next dev builds again, maybe those changes affect this as well somehow.

**Comment by schmiddel89** [comment]
Hmm weird thing... I also tried the latest version, but the issue still occurs.. :(

I think I give up... Nobody is able to fix the problem >.>

**Comment by Morphan1** [comment]
Try the latest development build, I had an idea that may work

**Comment by Morphan1** [comment]
Has this been resolved yet?

**Comment by schmiddel89** [comment]
I thought it would be solved... but one of player on my server noticed the issue again... got the actual build.. Could you try to fix that :( it is urgent...
